name = "bluedice"
compatibility_date = "2026-07-04"
compatibility_flags = ["nodejs_compat"]
main = ".output/server/index.mjs"
workers_dev = false

[assets]
directory = ".output/public"
binding = "ASSETS"

[[routes]]
pattern = "bluedice.savykids.com"
custom_domain = true
